# Generated by Django 4.0.5 on 2022-06-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='design',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
